version: '3.7'

services:
  clickhouse:
    container_name: clickhouse
    hostname: clickhouse
    image: yandex/clickhouse-server:21.3.20-alpine
    ports:
      - "19000:9000"
    volumes:
      - ./datasets:/datasets
